# Prometheus configuration for OpenCLIP service monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Rules for alerting
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # OpenCLIP Service
  - job_name: 'openclip-service'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['openclip-service:5000']
    scrape_timeout: 5s
    honor_labels: false
    params:
      format: ['prometheus']

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Prometheus Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Container Runtime Metrics (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
      scheme: http
      timeout: 10s
      api_version: v2

# Storage configuration
storage:
  tsdb:
    retention.time: 15d
    retention.size: 10GB
    
# Remote write (for Azure Monitor integration)
remote_write:
  - url: "https://your-workspace.ods.opinsights.azure.com/api/logs?api-version=2016-04-01"
    headers:
      Authorization: "Bearer YOUR_AZURE_TOKEN"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500