#!/bin/bash
echo "=== GitHub Copilot Agents Verification ==="
echo ""
echo "1. Agent files:"
ls -1 .github/agents/*.agent.md 2>/dev/null || echo "❌ No agent files found"
echo ""
echo "2. Prompt files:"
ls -1 .github/prompts/*.prompt.md 2>/dev/null || echo "❌ No prompt files found"
echo ""
echo "3. VS Code settings:"
cat .vscode/settings.json 2>/dev/null || echo "❌ No .vscode/settings.json found"
echo ""
echo "4. Constitution files:"
ls -1 CONSTITUTION*.md .specify/memory/constitution.md 2>/dev/null || echo "❌ Constitution files missing"
echo ""
echo "5. Git status:"
git status --short 2>/dev/null || echo "❌ Not a git repository"
echo ""
echo "=== Verification Complete ==="
